CREATE TABLE IF NOT EXISTS users(
  id INTEGER PRIMARY KEY NOT NULL,
  password VARCHAR(50) NOT NULL,
  email VARCHAR(300) UNIQUE NOT NULL,

  display_name VARCHAR(50),

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

 CREATE UNIQUE INDEX idx_users_email ON users (email);
