services:
  rp-api:
    container_name: rp-api
    image: rp-api
    build: .
    volumes:
      - .:/app:delegated
    environment:
      - DB_URL='sqlite3.db'
      - SECURE_COOKIES=false
      - ACCESS_TOKEN_SECRET=access_secret
      - REFRESH_TOKEN_SECRET=refresh_secret
    ports:
      - 3000:3000
    working_dir: /app
    command: ranked-pick-api
