services:
  rp-api:
    container_name: rp-api
    build: .
    volumes:
      - .:/app:delegated
      - $GOPATH:/go
      - $GOCACHE:/root/.cache/go-build
    environment:
      - SECURE_COOKIES=false
      - ACCESS_TOKEN_SECRET=access_secret
      - REFRESH_TOKEN_SECRET=refresh_secret
    ports:
      - 3000:3000
    working_dir: /app
    # command: sh -c "go build -o /usr/bin/ranked-pick-api github.com/carterjackson/ranked-pick-api/cmd/api && ranked-pick-api"
    command: ranked-pick-api
