services:
  rp-api:
    container_name: rp-api
    image: rp-api
    build: .
    volumes:
      - .:/app:delegated
    environment:
      - SECURE_STRICT=false
      - ACCESS_TOKEN_SECRET=dev_access_secret
      - REFRESH_TOKEN_SECRET=dev_refresh_secret
    ports:
      - 3000:3000
    working_dir: /app
    command: ranked-pick-api
