services:
  rp-api:
    container_name: rp-api
    build: .
    volumes:
      - .:/app:delegated
      - $GOPATH:/go
      - $GOCACHE:/root/.cache/go-build
    ports:
      - 3000:3000
    working_dir: /app
    command: sh -c "go build github.com/carterjackson/ranked-pick-api/cmd/ranked-pick-api && ./ranked-pick-api"
