BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS token_hashes (
  id INTEGER PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
	hash VARCHAR(60) NOT NULL,
	expires_at DATETIME NOT NULL,

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_token_hashes_user ON token_hashes (user_id);

COMMIT;
