// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Survey struct {
	ID          int64
	UserID      int64
	Title       string
	State       string
	Visibility  string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TokenHash struct {
	ID        int64
	UserID    int64
	Hash      string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	PasswordHash string
	Email        string
	DisplayName  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
