// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: surveys.sql

package db

import (
	"context"
	"database/sql"
)

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (
  user_id, title, state, visibility, description
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, user_id, title, state, visibility, description, created_at, updated_at
`

type CreateSurveyParams struct {
	UserID      int64
	Title       string
	State       string
	Visibility  string
	Description sql.NullString
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (Survey, error) {
	row := q.db.QueryRowContext(ctx, createSurvey,
		arg.UserID,
		arg.Title,
		arg.State,
		arg.Visibility,
		arg.Description,
	)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.State,
		&i.Visibility,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSurvey = `-- name: DeleteSurvey :exec
DELETE FROM surveys
WHERE id = ?
`

func (q *Queries) DeleteSurvey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSurvey, id)
	return err
}

const getSurvey = `-- name: GetSurvey :one
SELECT id, user_id, title, state, visibility, description, created_at, updated_at FROM surveys
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSurvey(ctx context.Context, id int64) (Survey, error) {
	row := q.db.QueryRowContext(ctx, getSurvey, id)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.State,
		&i.Visibility,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSurveys = `-- name: ListSurveys :many
SELECT id, user_id, title, state, visibility, description, created_at, updated_at FROM surveys
ORDER BY id DESC LIMIT 100
`

func (q *Queries) ListSurveys(ctx context.Context) ([]Survey, error) {
	rows, err := q.db.QueryContext(ctx, listSurveys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Survey
	for rows.Next() {
		var i Survey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.State,
			&i.Visibility,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurvey = `-- name: UpdateSurvey :one
UPDATE surveys SET
user_id = coalesce(?1, user_id),
title = coalesce(?2, title),
state = coalesce(?3, state),
visibility = coalesce(?4, visibility),
description = coalesce(?5, description),
updated_at = CURRENT_TIMESTAMP
WHERE id = ?6
RETURNING id, user_id, title, state, visibility, description, created_at, updated_at
`

type UpdateSurveyParams struct {
	UserID      sql.NullInt64
	Title       sql.NullString
	State       sql.NullString
	Visibility  sql.NullString
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateSurvey(ctx context.Context, arg UpdateSurveyParams) (Survey, error) {
	row := q.db.QueryRowContext(ctx, updateSurvey,
		arg.UserID,
		arg.Title,
		arg.State,
		arg.Visibility,
		arg.Description,
		arg.ID,
	)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.State,
		&i.Visibility,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
