// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: token_hashes.sql

package db

import (
	"context"
	"time"
)

const createTokenHash = `-- name: CreateTokenHash :one
INSERT INTO token_hashes (
	user_id, hash, expires_at
) VALUES (
  ?, ?, ?
)
RETURNING id, user_id, hash, expires_at, created_at, updated_at
`

type CreateTokenHashParams struct {
	UserID    int64
	Hash      string
	ExpiresAt time.Time
}

func (q *Queries) CreateTokenHash(ctx context.Context, arg CreateTokenHashParams) (TokenHash, error) {
	row := q.db.QueryRowContext(ctx, createTokenHash, arg.UserID, arg.Hash, arg.ExpiresAt)
	var i TokenHash
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTokenHash = `-- name: DeleteTokenHash :exec
DELETE FROM token_hashes
WHERE hash = ?
`

func (q *Queries) DeleteTokenHash(ctx context.Context, hash string) error {
	_, err := q.db.ExecContext(ctx, deleteTokenHash, hash)
	return err
}

const readTokenHashByHash = `-- name: ReadTokenHashByHash :one
SELECT id, user_id, hash, expires_at, created_at, updated_at FROM token_hashes
WHERE hash = ? LIMIT 1
`

func (q *Queries) ReadTokenHashByHash(ctx context.Context, hash string) (TokenHash, error) {
	row := q.db.QueryRowContext(ctx, readTokenHashByHash, hash)
	var i TokenHash
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
