// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  password_hash, username, display_name
) VALUES (
  ?, ?, ?
)
RETURNING id, username, password_hash, display_name, created_at, updated_at
`

type CreateUserParams struct {
	PasswordHash string
	Username     string
	DisplayName  sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.PasswordHash, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const readUser = `-- name: ReadUser :one
SELECT id, username, password_hash, display_name, created_at, updated_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) ReadUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, readUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readUserByUsername = `-- name: ReadUserByUsername :one
SELECT id, username, password_hash, display_name, created_at, updated_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) ReadUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, readUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
username = coalesce(?1, username),
display_name = coalesce(?2, display_name),
updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
RETURNING id, username, password_hash, display_name, created_at, updated_at
`

type UpdateUserParams struct {
	Username    sql.NullString
	DisplayName sql.NullString
	ID          int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Username, arg.DisplayName, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET
password_hash = ?,
updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, password_hash, display_name, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
