name: Deploy

on:
push:
  branches: [ "main" ]
  workflow_run:
    workflows: ["Go build + test"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o rp-api ./cmd/api/main.go

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "rp-api"
        target: "/usr/bin"

    # - name: Executing remote  command
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PORT: ${{ secrets.PORT }}
    #     KEY: ${{ secrets.SSHKEY }}
    #     script:
