name: Deploy

on:
  push:
    branches: [ "main" ]
    workflow_run:
      workflows: ["Go build + test"]
      types:
        - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o rp-api ./cmd/api/main.go

    # NOTE: Running user must have sudo access to `/bin/systemctl stop rp-api`
    - name: Stopping rp-api on host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: sudo systemctl stop rp-api

    - name: Copy executable via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "rp-api"
        target: "/usr/local/bin"
        overwrite: true

    - name: Copy migrations via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "./migrations"
        target: "/etc/ranked-pick-api"
        overwrite: true

    # NOTE: Running user must have sudo access to `/bin/systemctl start rp-api`
    - name: Restarting rp-api on host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: sudo systemctl start rp-api
